<?php

namespace App\Controller;


use Cake\I18n\I18n;

class ImagensController extends AppController{

    public $uses = array();
    public $components= array('Upload');

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Upload');
    }

    public function index() //Land Page do utilizador onde será listado os registo existentes na tabela
    {
        $this->Imagens->recursive=0;
        $this->paginate = [
            'contain' => ['Utilizador'],
            'limit' =>10 //Limite máximo de registos mostrados por página
        ];
        $this->set('imagens', $this->paginate());
    }

}
